
version: "3"
services:
  docker-postgre:
    image: postgres:latest
    container_name: my-postgres-container
    environment:
      - POSTGRES_DB= MyDB
      - POSTGRES_PASSWORD=root56789
      - POSTGRES_USER=root
    ports:
      - 5432:5423

  app:
    build: .
    image: download-upload:latest
    container_name: my-spring-boot-container
    ports:
      - 8081:8081
    environment:
      - DATABASE_USER= root
      - DATABASE_PASSWORD= root56789
      - DATABASE_NAME= MyDB
      - DATABASE_PORT= 5423

    depends_on:
      - docker-postgre



